apiVersion: v1
kind: Secret
metadata:
  name: db-secret
stringData:
  username: "keycloak"
  password: "password"
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-secret
stringData:
  username: "admin"
  password: "password"
