apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vrelte-secret-store
    kind: SecretStore
  target:
    name: admin-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: admin-secret
        property: username
    - secretKey: password
      remoteRef:
        key: admin-secret
        property: password