apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`auth.example.org`)
      kind: Rule
      services:
        - name: keycloak-service
          port: 80
  tls: {}