resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml

generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app: postgres
    includeSelectors: true
    includeTemplates: true