apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - ./postgres
  
patches:
  - path: volume-patch.yaml
  - path: secret-env-patch.yaml

configMapGenerator:
  - name: env
    envs:
      - keycloak.env
  - name: db-env
    envs:
      - db.env

namePrefix: keycloak-

labels:
  - pairs:
      app: keycloak
    includeSelectors: true
    includeTemplates: true