apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
        - name: keycloak
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: KC_DB_URL_DATABASE
              valueFrom:
                 configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: KC_DB_URL_HOST
              value: "keycloak-postgres-service"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_BOOTSTRAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: username
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-secret
                  key: password