apiVersion: v1
kind: Pod
metadata:
  name: theme-uploader
spec:
  restartPolicy: Never
  containers:
    - name: uploader
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: keycloak-pvc